[build-system]
requires = [
    "robotpy-build<2023.0.0,>=2022.2.0",
    "robotpy-wpiutil<2023.0.0,>=2022.4.1.1",
    "robotpy-wpimath<2023.0.0,>=2022.4.1.0",
    "robotpy-hal<2023.0.0,>=2022.4.1.0",
    "pyntcore<2023.0.0,>=2022.4.1.0",
]

[tool.robotpy-build]
base_package = "halsim_gui"


[tool.robotpy-build.wrappers."halsim_gui".maven_lib_download]
artifact_id = "halsim_gui"
group_id = "edu.wpi.first.halsim"
repo_url = "https://frcmaven.wpi.edu/artifactory/release"
version = "2022.4.1"

dlopenlibs = ["halsim_gui"]

# TODO: make this a namespace package?
[tool.robotpy-build.wrappers."halsim_gui"]
name = "halsim_gui"
depends = ["wpiutil", "wpiHal", "ntcore", "wpimath_cpp"]

[tool.robotpy-build.metadata]
name = "robotpy-halsim-gui"
description = "WPILib command framework"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-halsim-gui"
license = "BSD-3-Clause"
install_requires = [
    "robotpy-wpiutil<2023.0.0,>=2022.4.1.1",
    "robotpy-wpimath<2023.0.0,>=2022.4.1.0",
    "robotpy-hal<2023.0.0,>=2022.4.1.0",
    "pyntcore<2023.0.0,>=2022.4.1.0",
]
